target: all
multitenancy_enabled: true
stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: info

query_frontend:
  multi_tenant_queries_enabled: true
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831
        thrift_http:
          endpoint: 0.0.0.0:14268
    opencensus:
      endpoint: 0.0.0.0:55678
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    zipkin:
      endpoint: 0.0.0.0:9411


ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

metrics_generator:
  processor:
    span_metrics:
      dimensions: []
      filter_policies:
        - include:
            attributes:
              - key: kind
                value: SPAN_KIND_SERVER
            match_type: strict
      histogram_buckets:
        - 0.001
        - 0.05
        - 0.1
        - 0.5
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 30
  storage:
    path: /var/tempo/wal
    remote_write:
      - send_exemplars: true
        url: http://mimir:8080/api/v1/push
    remote_write_flush_deadline: 1m
storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

overrides:
  metrics_generator_processors:
    - service-graphs
    - span-metrics
